### ISSUE TITLE
Partitioned code rewrite: Memory allocation issues

### ISSUE THREAD

**Issue by akashchouhan16** [Blumea/Blumea#18]
- Memory allocation issues cause the app to crash, and exceptions are not handled
- needs completely rewritten logic

**blumea-serverless app crash preview while accessing the partitioned bloom api** 
![blumea-serverless-appcrash](https://user-images.githubusercontent.com/56465610/229298599-ac70815b-0bc4-48d3-80f4-f289dca06246.jpg)

**Comment by singhtaran1005** [comment]
https://github.com/Blumea/Blumea/pull/28
Updated partiioned bloom filter to fix memory allocation issue
