### ISSUE TITLE
Partitioned Bloom Bug - find() & insert() fails

### ISSUE THREAD

**Issue by akashchouhan16** [Blumea/Blumea#43]
## Probable cause:
- Invalid variable declarations. Could be because of an uninitialized **numberOfPartitions** array.
## Blumea Logger preview:
![blumea-partitioned-bug](https://user-images.githubusercontent.com/56465610/233051814-3958d3f6-6a92-4e9d-82c9-f01c10badd7f.jpg)

**Comment by singhtaran1005** [comment]
https://github.com/Blumea/Blumea/pull/45

**Comment by akashchouhan16** [comment]
All checks passed with manual test
```bash
  npm run test/partitioned
```
